--ROW, PAGE, or NONE

--Table creation statement
CREATE TABLE tHeap(Col1 INT, Col2 VARCHAR(30))
WITH(DATA_COMPRESSION = ROW);

CREATE TABLE tCI(Col1 INT, Col2 VARCHAR(30),
CONSTRAINT PK_tCI PRIMARY KEY CLUSTERED 
(Col1)
WITH(DATA_COMPRESSION = ROW)
);

--Index creation statement
CREATE NONCLUSTERED INDEX [IX_Col2] ON [dbo].[tHeap]
(Col2)
WITH (DATA_COMPRESSION = ROW);
GO

CREATE CLUSTERED INDEX [PK_Col1] ON [dbo].[tHeap]
(Col1)
WITH (DATA_COMPRESSION = ROW);
GO

--Rebuild statements
ALTER INDEX IX_Col2 ON dbo.tHeap 
REBUILD WITH (DATA_COMPRESSION = ROW);

ALTER TABLE tHEAP REBUILD WITH(DATA_COMPRESSION = ROW);


