//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40607.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.40607.42.
// 
namespace SoapWSSecurity.zmv921 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    using System.Data.SqlTypes;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="pubs_sslint_endpointSoap", Namespace="http://foo.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xml))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SqlParameter[]))]
    public class pubs_sslint_endpoint : System.Web.Services.Protocols.SoapHttpClientProtocol {

        public SqlSoapHeader.Security sqlSecurityValue;

        /// <remarks/>
        public pubs_sslint_endpoint() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["SoapWSSecurity.zmv921.pubs_sslint_endpoint"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "https://zmv92/pubs_sslint/";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/sqlserver/2004/SOAPsqlbatch", RequestNamespace="http://schemas.microsoft.com/sqlserver/2004/SOAP", ResponseNamespace="http://schemas.microsoft.com/sqlserver/2004/SOAP", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlResultCode", typeof(int), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlTransaction), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlRowCount), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlXml", typeof(System.Xml.XmlNode), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlMessage), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlRowSet", typeof(System.Data.DataSet), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("sqlSecurityValue", Direction = SoapHeaderDirection.InOut)]
        public object[] sqlbatch(string BatchCommands, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlParameter", IsNullable=false)] ref SqlParameter[] Parameters) {
            object[] results = this.Invoke("sqlbatch", new object[] {
                        BatchCommands,
                        Parameters});
            Parameters = ((SqlParameter[])(results[1]));
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsqlbatch(string BatchCommands, SqlParameter[] Parameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sqlbatch", new object[] {
                        BatchCommands,
                        Parameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] Endsqlbatch(System.IAsyncResult asyncResult, out SqlParameter[] Parameters) {
            object[] results = this.EndInvoke(asyncResult);
            Parameters = ((SqlParameter[])(results[1]));
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:www-develop-com:invoicesbyroyalty", RequestNamespace="urn:www-develop-com:invoices", ResponseNamespace="urn:www-develop-com:invoices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlResultCode", typeof(int), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlTransaction), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlRowCount), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlXml", typeof(System.Xml.XmlNode), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(typeof(SqlMessage), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("SqlRowSet", typeof(System.Data.DataSet), Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlResultStream", IsNullable=false)]
        public object[] byroyalty([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Data.SqlTypes.SqlInt32 percentage) {
            object[] results = this.Invoke("byroyalty", new object[] {
                        percentage});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginbyroyalty(System.Data.SqlTypes.SqlInt32 percentage, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("byroyalty", new object[] {
                        percentage}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] Endbyroyalty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlParameter")]
    public class SqlParameter {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Value;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(sqlDbTypeEnum.NVarChar)]
        public sqlDbTypeEnum sqlDbType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ParameterDirection.Input)]
        public ParameterDirection direction;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "1")]
        public long maxLength;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "18")]
        public byte precision;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
        public byte scale;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string clrTypeName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(sqlCompareOptionsList.None)]
        public sqlCompareOptionsList sqlCompareOptions;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-1)]
        public int localeId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int sqlCollationVersion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int sqlSortId;
        
        public SqlParameter() {
            this.sqlDbType = sqlDbTypeEnum.NVarChar;
            this.direction = ParameterDirection.Input;
            this.maxLength = ((long)(1));
            this.precision = ((byte)(18));
            this.scale = ((byte)(0));
            this.clrTypeName = "";
            this.sqlCompareOptions = sqlCompareOptionsList.None;
            this.localeId = -1;
            this.sqlCollationVersion = 0;
            this.sqlSortId = 0;
        }
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/sqltypes")]
    public class xml {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlTransaction")]
    public class SqlTransaction {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Descriptor;
        
        /// <remarks/>
        public SqlTransactionType Type;
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlTransaction")]
    public enum SqlTransactionType {
        
        /// <remarks/>
        Begin,
        
        /// <remarks/>
        Commit,
        
        /// <remarks/>
        Rollback,
        
        /// <remarks/>
        EnlistDTC,
        
        /// <remarks/>
        Defect,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlRowCount")]
    public class SqlRowCount {
        
        /// <remarks/>
        public long Count;
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlMessage")]
    public class SqlMessage {
        
        /// <remarks/>
        public int Class;
        
        /// <remarks/>
        public int LineNumber;
        
        /// <remarks/>
        public string Message;
        
        /// <remarks/>
        public int Number;
        
        /// <remarks/>
        public string Procedure;
        
        /// <remarks/>
        public string Server;
        
        /// <remarks/>
        public string Source;
        
        /// <remarks/>
        public int State;
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/sqltypes")]
    public enum sqlDbTypeEnum {
        
        /// <remarks/>
        BigInt,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        Bit,
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Int,
        
        /// <remarks/>
        Money,
        
        /// <remarks/>
        NChar,
        
        /// <remarks/>
        NText,
        
        /// <remarks/>
        NVarChar,
        
        /// <remarks/>
        Real,
        
        /// <remarks/>
        SmallDateTime,
        
        /// <remarks/>
        SmallInt,
        
        /// <remarks/>
        SmallMoney,
        
        /// <remarks/>
        Sql_Variant,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Timestamp,
        
        /// <remarks/>
        TinyInt,
        
        /// <remarks/>
        Udt,
        
        /// <remarks/>
        UniqueIdentifier,
        
        /// <remarks/>
        UtcDateTime,
        
        /// <remarks/>
        VarBinary,
        
        /// <remarks/>
        VarChar,
        
        /// <remarks/>
        Xml,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/SOAP/types/SqlParameter")]
    public enum ParameterDirection {
        
        /// <remarks/>
        Input,
        
        /// <remarks/>
        InputOutput,
    }
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.FlagsAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/sqlserver/2004/sqltypes")]
    public enum sqlCompareOptionsList {
        
        /// <remarks/>
        Default = 1,
        
        /// <remarks/>
        None = 2,
        
        /// <remarks/>
        IgnoreCase = 4,
        
        /// <remarks/>
        IgnoreNonSpace = 8,
        
        /// <remarks/>
        IgnoreKanaType = 16,
        
        /// <remarks/>
        IgnoreWidth = 32,
        
        /// <remarks/>
        BinarySort = 64,
        
        /// <remarks/>
        BinarySort2 = 128,
    }
}
